### ISSUE TITLE
src/index.html template not being used

### ISSUE THREAD

**Issue by n-k** [csharad/cargo-ruukh#16]
Adding an src/index.html file with a modified template does not seem to work. Is there an example of how to use this feature?

**Comment by csharad** [comment]
I have updated the README. Tell me if you are still having an issue.

**Comment by n-k** [comment]
Thanks @csharad for your quick response . Works perfectly by following the updated README.

**Comment by csharad** [comment]
Great! Closing this as the issue is resolved.
